### ISSUE TITLE
CHECK_API_TIME配置项无效

### ISSUE THREAD

**Issue by cannedH** [xuanerwa/zhenxun_github_sub#2]
**系统版本：Windows11
Bot版本：v0.2.4-fix2
数据库：sqlite**

在修改config.yaml、sql语句：exec update github_sub set update_time=21600后仍然为30s的间隔检测更新。
同时默认30s有点频繁了，希望能延长，个人倾向于1h以上。

![屏幕截图 2024-11-18 222913](https://github.com/user-attachments/assets/fd0cec77-ca07-474e-9b3d-33386b3ced57)
![屏幕截图 2024-11-18 222435](https://github.com/user-attachments/assets/5ae8f0f4-7706-4b67-b4ab-ab31ca7b7489)
![屏幕截图 2024-11-18 223021](https://github.com/user-attachments/assets/3f0aae3c-4a1b-4db0-9325-c06f18d904cf)
![屏幕截图 2024-11-18 223125](https://github.com/user-attachments/assets/d3c5b90f-e2c1-426d-be04-35e13146c929)

**Comment by xuanerwa** [comment]
https://github.com/xuanerwa/zhenxun_github_sub/commit/f524632f78d27f9893beebdf709e0e7885cd08f1
已修复，延长并没有实际意义，因为用的是etag，不会有频率限制，不能实时推送是github接口本身有延迟的原因

**Comment by cannedH** [comment]
好的感谢🙏🏻

**Comment by devil233-ui** [comment]
> [f524632](https://github.com/xuanerwa/zhenxun_github_sub/commit/f524632f78d27f9893beebdf709e0e7885cd08f1) 已修复，延长并没有实际意义，因为用的是etag，不会有频率限制，不能实时推送是github接口本身有延迟的原因

问题是检测频率这么高对服务器没有负担么（）
另外一问他这sql语句值类型都不对是怎么执行成功的，不同数据库导致的？
